name: framy
description: Framy generates svg file that shows nesting hierarchy of the views in the app.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # Required to use framy to take screenshots.
  flutter_driver:
    sdk: flutter

dev_dependencies:
  # Used by tests. Not required to use `framy`.
  test: ^1.6.0

